-- MySQL Script generated by MySQL Workbench
-- Mon Sep  7 15:26:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  `perfiles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `id` INT NOT NULL,
  `nombres` VARCHAR(255) NULL,
  `apellidos` VARCHAR(255) NULL,
  `tipo_documento` VARCHAR(45) NULL,
  `documento` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `correo` VARCHAR(120) NULL,
  `genero` VARCHAR(1) NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedula_UNIQUE` (`tipo_documento` ASC) VISIBLE,
  INDEX `fk_personas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_personas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT(2) NOT NULL,
  `nombre` VARCHAR(120) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciudades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT(3) NOT NULL,
  `nombre` VARCHAR(120) NULL,
  `departamentos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudades_departamentos_idx` (`departamentos_id` ASC) VISIBLE,
  CONSTRAINT `fk_ciudades_departamentos`
    FOREIGN KEY (`departamentos_id`)
    REFERENCES `mydb`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NULL,
  `barrio` VARCHAR(255) NULL,
  `zona` VARCHAR(45) NULL,
  `ciudades_id` INT NOT NULL,
  `personas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_direcciones_ciudades1_idx` (`ciudades_id` ASC) VISIBLE,
  INDEX `fk_direcciones_personas1_idx` (`personas_id` ASC) VISIBLE,
  CONSTRAINT `fk_direcciones_ciudades1`
    FOREIGN KEY (`ciudades_id`)
    REFERENCES `mydb`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direcciones_personas1`
    FOREIGN KEY (`personas_id`)
    REFERENCES `mydb`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pacientes_personas1_idx` (`personas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pacientes_personas1`
    FOREIGN KEY (`personas_id`)
    REFERENCES `mydb`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historia_clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historia_clinica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NULL,
  `movil` VARCHAR(10) NULL,
  `horas_espera` INT(3) NULL,
  `fecha` DATE NULL,
  `motivo` TEXT NULL,
  `diagnostico` TEXT NULL,
  `observacion` TEXT NULL,
  `des_entrada_paciente` TEXT NULL,
  `des_novedad_paciente` TEXT NULL,
  `triage` INT(1) NULL,
  `sv_ta` VARCHAR(45) NULL,
  `tam` VARCHAR(45) NULL,
  `tc` VARCHAR(45) NULL,
  `sapo2` VARCHAR(45) NULL,
  `fr` VARCHAR(45) NULL,
  `fc` VARCHAR(45) NULL,
  `fcf` VARCHAR(45) NULL,
  `hora_solicitud` TIME NULL,
  `hora_salida` TIME NULL,
  `hora_llegada` TIME NULL,
  `hora_final` TIME NULL,
  `tipo_traslado` VARCHAR(45) NULL,
  `tipo_recorrido` VARCHAR(45) NULL,
  `ips_remitente` VARCHAR(255) NULL,
  `ips_receptora` VARCHAR(255) NULL,
  `ips_contraremision` VARCHAR(255) NULL,
  `medico` VARCHAR(255) NULL,
  `conductor` VARCHAR(255) NULL,
  `tipo_auxiliar` VARCHAR(45) NULL,
  `auxiliar` VARCHAR(255) NULL,
  `edad_paciente` VARCHAR(45) NULL,
  `sintomas` VARCHAR(255) NULL,
  `alergias` VARCHAR(255) NULL,
  `patologias` VARCHAR(255) NULL,
  `medicamentos` VARCHAR(255) NULL,
  `eventos_previos` VARCHAR(255) NULL,
  `ultima_ingesta` VARCHAR(255) NULL,
  `toxicos` VARCHAR(255) NULL,
  `gineco` VARCHAR(255) NULL,
  `quirurgico` VARCHAR(255) NULL,
  `examen_fisico` TEXT NULL,
  `tipo_seguridad` VARCHAR(45) NULL,
  `seguridad` VARCHAR(45) NULL,
  `pacientes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historia_clinica_pacientes1_idx` (`pacientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_historia_clinica_pacientes1`
    FOREIGN KEY (`pacientes_id`)
    REFERENCES `mydb`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`procedimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`procedimientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`procedimiento_historia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`procedimiento_historia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `historia_clinica_id` INT NOT NULL,
  `procedimientos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proceso_historia_historia_clinica1_idx` (`historia_clinica_id` ASC) VISIBLE,
  INDEX `fk_proceso_historia_procedimientos1_idx` (`procedimientos_id` ASC) VISIBLE,
  CONSTRAINT `fk_proceso_historia_historia_clinica1`
    FOREIGN KEY (`historia_clinica_id`)
    REFERENCES `mydb`.`historia_clinica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proceso_historia_procedimientos1`
    FOREIGN KEY (`procedimientos_id`)
    REFERENCES `mydb`.`procedimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`soportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`soportes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NULL,
  `historia_clinica_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_soportes_historia_clinica1_idx` (`historia_clinica_id` ASC) VISIBLE,
  CONSTRAINT `fk_soportes_historia_clinica1`
    FOREIGN KEY (`historia_clinica_id`)
    REFERENCES `mydb`.`historia_clinica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`firmas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asignacion` VARCHAR(45) NULL,
  `urlFirma` VARCHAR(255) NULL,
  `historia_clinica_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_firmas_historia_clinica1_idx` (`historia_clinica_id` ASC) VISIBLE,
  CONSTRAINT `fk_firmas_historia_clinica1`
    FOREIGN KEY (`historia_clinica_id`)
    REFERENCES `mydb`.`historia_clinica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NULL,
  `slug` VARCHAR(191) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id` INT NOT NULL,
  `name` VARCHAR(191) NULL,
  `slug` VARCHAR(191) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permission_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permissions_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_permission_role_permissions1_idx` (`permissions_id` ASC) VISIBLE,
  INDEX `fk_permission_role_roles1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_permission_role_permissions1`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `mydb`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_role_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permission_user` (
  `id` INT NOT NULL,
  `permissions_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_permission_user_permissions1_idx` (`permissions_id` ASC) VISIBLE,
  INDEX `fk_permission_user_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_permission_user_permissions1`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `mydb`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_user_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role_user` (
  `id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_user_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_role_user_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_user_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_user_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
